### ISSUE TITLE
Doctest is not running in CI and halts or fails locally

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#533]
Pre-Report Checklist
--------------------

- [x] I am running the latest version of mitiq
- [x] I checked to make sure that this bug has not already been reported

Issue Description
-----------------

I encounter two behaviours: 
1. The tests that run with `make doctest` halt indefinitely at the `Document: guide/guide-ibmq-backends` section. 
2. They pass there, but then fail later. 

Strangely, test pass on CI.

How to Reproduce
----------------
- fork the repo, open a new conda environment with Python 3.8, install mitiq with
```
pip install . -e 
pip install  -r requirements.txt
pip install  -r dev_requirements.txt 
pip install  -r docs/requirements.txt 
make doctest
```
Note that `pip install  -r docs/requirements.txt ` has some errors due to conflicts in cirq version requested. 
### Code Snippet

```python

```

### Error Output

```
  ~/gi/mitiq   pec-getting-started *2 ❯ make docs                 mitiqdev
make -C docs html
Running Sphinx v2.4.4
loading translations [Python]... not available for built-in messages
/opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages/m2r.py:652: RemovedInSphinx30Warning: app.add_source_parser() does not support suffix argument. Use app.add_source_suffix() instead.
  app.add_source_parser('.md', M2RParser)
loading pickled environment... done
loading intersphinx inventory from python37.inv...
loading intersphinx inventory from https://cirq.readthedocs.io/en/stable/objects.inv...
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'python37.inv' not fetchable due to <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/Users/nathanshammah/github/mitiq/docs/source/python37.inv'
loading intersphinx inventory from http://docs.rigetti.com/en/stable/objects.inv...
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://cirq.readthedocs.io/en/stable/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://cirq.readthedocs.io/en/stable/objects.inv
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'http://docs.rigetti.com/en/stable/objects.inv' not fetchable due to <class 'requests.exceptions.ConnectionError'>: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 21 source files that are out of date
updating environment: 0 added, 3 changed, 0 removed
reading sources... [100%] guide/guide-getting-started
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/nathanshammah/github/mitiq/docs/source/guide/_guide-zne-lindblad.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] zz_bibliography
/Users/nathanshammah/github/mitiq/docs/source/README.rst:130: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.FakeNodesFactory:1: WARNING: citation not found: De2020polynomial
/Users/nathanshammah/github/mitiq/docs/source/contributing_docs.rst:82: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
/Users/nathanshammah/github/mitiq/docs/source/contributing_docs.rst:104: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
/Users/nathanshammah/github/mitiq/docs/source/contributing_docs.rst:132: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
/Users/nathanshammah/github/mitiq/docs/source/contributing_docs.rst:203: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
/Users/nathanshammah/github/mitiq/docs/source/contributing_docs.rst:214: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
/Users/nathanshammah/github/mitiq/docs/source/contributing_docs.rst:222: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
/Users/nathanshammah/github/mitiq/docs/source/contributing_docs.rst:234: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
/Users/nathanshammah/github/mitiq/docs/source/contributing_docs.rst:251: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
/Users/nathanshammah/github/mitiq/docs/source/contributing_docs.rst:296: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
/Users/nathanshammah/github/mitiq/docs/source/guide/guide-error-mitigation.rst:29: WARNING: undefined label: guide_qem_what_not (if the link has no caption the label must precede a section header)
/Users/nathanshammah/github/mitiq/docs/source/guide/guide-error-mitigation.rst:56: WARNING: undefined label: guide-folding (if the link has no caption the label must precede a section header)
/Users/nathanshammah/github/mitiq/docs/source/guide/guide-getting-started.rst:175: WARNING: undefined label: guide-factories (if the link has no caption the label must precede a section header)
/Users/nathanshammah/github/mitiq/docs/source/guide/guide-getting-started.rst:178: WARNING: undefined label: guide-folding (if the link has no caption the label must precede a section header)
generating indices...  genindex py-modindexdone
highlighting module code... [100%] mitiq.zne.zne
writing additional pages...  searchdone
copying images... [100%] guide/../img/maxcut-qaoa-mitigated-landscape.png
copying downloadable files... [100%] mitiq.bib
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 19 warnings.

The HTML pages are in build/html.
  ~/gi/mitiq   pec-getting-started *2 ❯ pip install -r docs/requirements.txt

Collecting tensorflow~=2.3.1
  Downloading tensorflow-2.3.2-cp38-cp38-macosx_10_11_x86_64.whl (165.2 MB)
     |████████████████████████████████| 165.2 MB 3.3 MB/s
Requirement already satisfied: numpy<1.19.0,>=1.16.0 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from tensorflow~=2.3.1->-r docs/requirements.txt (line 1)) (1.18.5)
Requirement already satisfied: six>=1.12.0 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from tensorflow~=2.3.1->-r docs/requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: wheel>=0.26 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from tensorflow~=2.3.1->-r docs/requirements.txt (line 1)) (0.36.2)
Requirement already satisfied: grpcio>=1.8.6 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from tensorflow~=2.3.1->-r docs/requirements.txt (line 1)) (1.35.0)
Requirement already satisfied: protobuf>=3.9.2 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from tensorflow~=2.3.1->-r docs/requirements.txt (line 1)) (3.13.0)
Collecting astunparse==1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting gast==0.3.3
  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
Collecting tensorflow-quantum~=0.4.0
  Using cached tensorflow_quantum-0.4.0-cp38-cp38-macosx_10_11_x86_64.whl (4.6 MB)
Collecting cirq==0.9.1
  Using cached cirq-0.9.1-py3-none-any.whl (1.6 MB)
Requirement already satisfied: google-api-core[grpc]<2.0.0dev,>=1.14.0 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (1.25.1)
Requirement already satisfied: scipy in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (1.4.1)
Requirement already satisfied: matplotlib~=3.0 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (3.2.2)
Requirement already satisfied: requests~=2.18 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (2.25.1)
Requirement already satisfied: sortedcontainers~=2.0 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (2.3.0)
Requirement already satisfied: pandas in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (1.2.1)
Requirement already satisfied: networkx~=2.4 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (2.5)
Requirement already satisfied: typing-extensions in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (3.7.4.3)
Collecting sympy==1.5
  Using cached sympy-1.5-py2.py3-none-any.whl (5.6 MB)
Requirement already satisfied: mpmath>=0.19 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from sympy==1.5->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (1.1.0)
Collecting absl-py>=0.7.0
  Using cached absl_py-0.11.0-py3-none-any.whl (127 kB)
Collecting freezegun~=0.3.15
  Using cached freezegun-0.3.15-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: python-dateutil!=2.0,>=1.0 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from freezegun~=0.3.15->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (2.8.1)
Requirement already satisfied: pytz in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (2021.1)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (1.52.0)
Requirement already satisfied: setuptools>=40.3.0 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (52.0.0.post20210125)
Requirement already satisfied: google-auth<2.0dev,>=1.21.1 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (1.25.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.14.0->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (4.7)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.14.0->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.14.0->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (4.2.1)
Collecting google-pasta>=0.1.8
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting h5py<2.11.0,>=2.10.0
  Using cached h5py-2.10.0-cp38-cp38-macosx_10_9_x86_64.whl (3.0 MB)
Collecting keras-preprocessing<1.2,>=1.1.1
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from matplotlib~=3.0->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from matplotlib~=3.0->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from matplotlib~=3.0->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (2.4.7)
Requirement already satisfied: decorator>=4.3.0 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from networkx~=2.4->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (4.4.2)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting protobuf>=3.9.2
  Using cached protobuf-3.12.4-cp38-cp38-macosx_10_9_x86_64.whl (1.3 MB)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.14.0->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (0.4.8)
Requirement already satisfied: chardet<5,>=3.0.2 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from requests~=2.18->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from requests~=2.18->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from requests~=2.18->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (1.26.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages (from requests~=2.18->cirq==0.9.1->tensorflow-quantum~=0.4.0->-r docs/requirements.txt (line 2)) (2020.12.5)
Collecting tensorboard<3,>=2.3.0
  Using cached tensorboard-2.4.1-py3-none-any.whl (10.6 MB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.2-py2.py3-none-any.whl (18 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.3.3-py3-none-any.whl (96 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
Collecting tensorflow-estimator<2.4.0,>=2.3.0
  Using cached tensorflow_estimator-2.3.0-py2.py3-none-any.whl (459 kB)
Collecting termcolor>=1.1.0
  Using cached termcolor-1.1.0-py3-none-any.whl
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting wrapt>=1.11.1
  Using cached wrapt-1.12.1-cp38-cp38-macosx_10_14_x86_64.whl
Installing collected packages: protobuf, oauthlib, requests-oauthlib, werkzeug, tensorboard-plugin-wit, sympy, markdown, google-auth-oauthlib, freezegun, absl-py, wrapt, termcolor, tensorflow-estimator, tensorboard, opt-einsum, keras-preprocessing, h5py, google-pasta, gast, cirq, astunparse, tensorflow-quantum, tensorflow
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.13.0
    Uninstalling protobuf-3.13.0:
      Successfully uninstalled protobuf-3.13.0
  Attempting uninstall: sympy
    Found existing installation: sympy 1.7.1
    Uninstalling sympy-1.7.1:
      Successfully uninstalled sympy-1.7.1
  Attempting uninstall: h5py
    Found existing installation: h5py 3.1.0
    Uninstalling h5py-3.1.0:
      Successfully uninstalled h5py-3.1.0
  Attempting uninstall: cirq
    Found existing installation: cirq 0.10.0.dev20201203012958
    Uninstalling cirq-0.10.0.dev20201203012958:
      Successfully uninstalled cirq-0.10.0.dev20201203012958
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mitiq 0.5.0.dev0 requires cirq==0.10.0.dev20201203012958, but you have cirq 0.9.1 which is incompatible.
Successfully installed absl-py-0.11.0 astunparse-1.6.3 cirq-0.9.1 freezegun-0.3.15 gast-0.3.3 google-auth-oauthlib-0.4.2 google-pasta-0.2.0 h5py-2.10.0 keras-preprocessing-1.1.2 markdown-3.3.3 oauthlib-3.1.0 opt-einsum-3.3.0 protobuf-3.12.4 requests-oauthlib-1.3.0 sympy-1.5 tensorboard-2.4.1 tensorboard-plugin-wit-1.8.0 tensorflow-2.3.2 tensorflow-estimator-2.3.0 tensorflow-quantum-0.4.0 termcolor-1.1.0 werkzeug-1.0.1 wrapt-1.12.1
  ~/gi/mitiq   pec-getting-started *2 ❯ make doctest        55s  mitiqdev
make -C docs doctest
Running Sphinx v2.4.4
loading translations [Python]... not available for built-in messages
/opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages/m2r.py:652: RemovedInSphinx30Warning: app.add_source_parser() does not support suffix argument. Use app.add_source_suffix() instead.
  app.add_source_parser('.md', M2RParser)
loading pickled environment... done
loading intersphinx inventory from python37.inv...
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'python37.inv' not fetchable due to <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/Users/nathanshammah/github/mitiq/docs/source/python37.inv'
loading intersphinx inventory from https://cirq.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from http://docs.rigetti.com/en/stable/objects.inv...
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'http://docs.rigetti.com/en/stable/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 500 Server Error: Internal Server Error for url: https://docs.rigetti.com/en/stable/objects.inv
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://cirq.readthedocs.io/en/stable/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://cirq.readthedocs.io/en/stable/objects.inv
building [mo]: targets for 0 po files that are out of date
building [doctest]: targets for 21 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] apidoc
/Users/nathanshammah/github/mitiq/mitiq/benchmarks/maxcut.py:docstring of mitiq.benchmarks.maxcut.make_maxcut:19: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/nathanshammah/github/mitiq/docs/source/apidoc.rst:21: WARNING: Title underline too short.

Random Circuits
^^^^^^^^^^^^^^
/Users/nathanshammah/github/mitiq/docs/source/apidoc.rst:21: WARNING: Title underline too short.

Random Circuits
^^^^^^^^^^^^^^
/Users/nathanshammah/github/mitiq/mitiq/benchmarks/random_circuits.py:docstring of mitiq.benchmarks.random_circuits.sample_projector:10: WARNING: Inline substitution_reference start-string without end-string.
/Users/nathanshammah/github/mitiq/docs/source/apidoc.rst:26: WARNING: Title underline too short.

Randomized Benchmarking
^^^^^^^^^^^^^^
/Users/nathanshammah/github/mitiq/docs/source/apidoc.rst:26: WARNING: Title underline too short.

Randomized Benchmarking
^^^^^^^^^^^^^^
/Users/nathanshammah/github/mitiq/mitiq/mitiq_qiskit/conversions.py:docstring of mitiq.mitiq_qiskit.conversions.to_qiskit:12: WARNING: Unexpected indentation.
/Users/nathanshammah/github/mitiq/mitiq/pec/representations/depolarizing.py:docstring of mitiq.pec.representations.depolarizing.represent_operation_with_local_depolarizing_noise:36: WARNING: Duplicate explicit target name: "temme2017".
/Users/nathanshammah/github/mitiq/mitiq/pec/pec.py:docstring of mitiq.pec.pec.execute_with_pec:52: WARNING: Duplicate explicit target name: "temme2017".
/Users/nathanshammah/github/mitiq/mitiq/pec/pec.py:docstring of mitiq.pec.pec.execute_with_pec:62: WARNING: Duplicate explicit target name: "takagi2020".
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.AdaExpFactory.extrapolate:34: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.AdaExpFactory.extrapolate:36: WARNING: Unexpected indentation.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.AdaExpFactory.extrapolate:37: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.ExpFactory.extrapolate:35: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.ExpFactory.extrapolate:37: WARNING: Unexpected indentation.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.ExpFactory.extrapolate:38: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.LinearFactory.extrapolate:18: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.LinearFactory.extrapolate:20: WARNING: Unexpected indentation.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.LinearFactory.extrapolate:21: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.PolyExpFactory.extrapolate:44: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.PolyExpFactory.extrapolate:46: WARNING: Unexpected indentation.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.PolyExpFactory.extrapolate:47: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.PolyFactory.extrapolate:21: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.PolyFactory.extrapolate:23: WARNING: Unexpected indentation.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.PolyFactory.extrapolate:24: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.RichardsonFactory.extrapolate:18: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.RichardsonFactory.extrapolate:20: WARNING: Unexpected indentation.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.RichardsonFactory.extrapolate:21: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.mitiq_curve_fit:18: WARNING: Unexpected indentation.
/Users/nathanshammah/github/mitiq/mitiq/zne/inference.py:docstring of mitiq.zne.inference.mitiq_polyfit:16: WARNING: Unexpected indentation.
/Users/nathanshammah/github/mitiq/mitiq/zne/scaling/folding.py:docstring of mitiq.zne.scaling.folding.fold_gates_at_random:26: WARNING: Unexpected section title.

Gate key    | Gate
-------------------------
/Users/nathanshammah/github/mitiq/mitiq/zne/scaling/folding.py:docstring of mitiq.zne.scaling.folding.fold_gates_from_left:25: WARNING: Unexpected section title.

Gate key    | Gate
-------------------------
/Users/nathanshammah/github/mitiq/mitiq/zne/scaling/folding.py:docstring of mitiq.zne.scaling.folding.fold_gates_from_right:25: WARNING: Unexpected section title.

Gate key    | Gate
-------------------------
/Users/nathanshammah/github/mitiq/mitiq/pec/sampling.py:docstring of mitiq.pec.sampling.sample_sequence:4: WARNING: Undefined substitution referenced: "a".
/Users/nathanshammah/github/mitiq/mitiq/pec/sampling.py:docstring of mitiq.pec.sampling.sample_sequence:4: WARNING: Undefined substitution referenced: "a".
/Users/nathanshammah/github/mitiq/mitiq/pec/sampling.py:docstring of mitiq.pec.sampling.sample_sequence:4: WARNING: Undefined substitution referenced: "b".
/Users/nathanshammah/github/mitiq/mitiq/pec/sampling.py:docstring of mitiq.pec.sampling.sample_sequence:4: WARNING: Undefined substitution referenced: "b".
/Users/nathanshammah/github/mitiq/mitiq/pec/sampling.py:docstring of mitiq.pec.sampling.sample_sequence:4: WARNING: Undefined substitution referenced: "a".
/Users/nathanshammah/github/mitiq/mitiq/pec/sampling.py:docstring of mitiq.pec.sampling.sample_sequence:4: WARNING: Undefined substitution referenced: "b".
/Users/nathanshammah/github/mitiq/mitiq/pec/sampling.py:docstring of mitiq.pec.sampling.sample_sequence:4: WARNING: Undefined substitution referenced: "a".
/Users/nathanshammah/github/mitiq/mitiq/pec/sampling.py:docstring of mitiq.pec.sampling.sample_sequence:4: WARNING: Undefined substitution referenced: "b".
/Users/nathanshammah/github/mitiq/mitiq/pec/representations/depolarizing.py:docstring of mitiq.pec.representations.depolarizing.represent_operation_with_local_depolarizing_noise:36: WARNING: duplicate citation Temme2017, other instance in /Users/nathanshammah/github/mitiq/docs/source/apidoc.rst
/Users/nathanshammah/github/mitiq/mitiq/pec/pec.py:docstring of mitiq.pec.pec.execute_with_pec:52: WARNING: duplicate citation Temme2017, other instance in /Users/nathanshammah/github/mitiq/docs/source/apidoc.rst
/Users/nathanshammah/github/mitiq/mitiq/pec/pec.py:docstring of mitiq.pec.pec.execute_with_pec:62: WARNING: duplicate citation Takagi2020, other instance in /Users/nathanshammah/github/mitiq/docs/source/apidoc.rst
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/nathanshammah/github/mitiq/docs/source/guide/_guide-zne-lindblad.rst: WARNING: document isn't included in any toctree
done
running tests...

Document: guide/guide-getting-started
-------------------------------------
1 items passed all tests:
  10 tests in default
10 tests in 1 items.
10 passed and 0 failed.
Test passed.

Document: guide/guide-ibmq-backends
---------------------------
ocument: guide/guide-executors
-------------------------------
/opt/miniconda3/envs/mitiqdev/lib/python3.8/site-packages/pyquil/api/_compiler.py:398: UserWarning: No quilc server running at tcp://127.0.0.1:5555. Compilation using quilc will not be available.
  warnings.warn(f"{e}. Compilation using quilc will not be available.")
**********************************************************************
File "guide/guide-executors.rst", line 453, in default
Failed example:
    from pyquil import Program, get_qc
    from pyquil.gates import MEASURE, RESET, X

    from mitiq.mitiq_pyquil.compiler import basic_compile
    from mitiq.mitiq_pyquil.pyquil_utils import ground_state_expectation

    # replace with qpu = get_qc("Aspen-8") to run on the Aspen-8 QPU
    qpu = get_qc("2q-pyqvm")

    def executor(program: Program, shots: int = 1000) -> float:
        p = Program()

        # add reset
        p += RESET()

        # add main body program
        p += program.copy()

        # add memory declaration
        qubits = p.get_qubits()
        ro = p.declare("ro", "BIT", len(qubits))

        # add measurements
        for idx, q in enumerate(qubits):
            p += MEASURE(q, ro[idx])

        # add numshots
        p.wrap_in_numshots_loop(shots)

        # nativize the circuit
        p = basic_compile(p)

        # compile the circuit
        b = qpu.compiler.native_quil_to_executable(p)

        # run the circuit, collect bitstrings
        qpu.reset()
        results = qpu.run(b)

        # compute ground state expectation value
        return ground_state_expectation(results)

    # prepare state |11>
    program = Program()
    program += X(0)
    program += X(1)

    # should give 0.0 with a noiseless backend
    executor(program)
Exception raised:
    Traceback (most recent call last):
      File "/opt/miniconda3/envs/mitiqdev/lib/python3.8/doctest.py", line 1328, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[0]>", line 49, in <module>
        executor(program)
      File "<doctest default[0]>", line 31, in executor
        p = basic_compile(p)
      File "/Users/nathanshammah/github/mitiq/mitiq/mitiq_pyquil/compiler.py", line 244, in basic_compile
        if isinstance(inst, Gate):
    TypeError: isinstance() arg 2 must be a type or tuple of types
**********************************************************************
File "guide/guide-executors.rst", line 557, in default
Failed example:
    assert executor(program) == 0.0
Exception raised:
    Traceback (most recent call last):
      File "/opt/miniconda3/envs/mitiqdev/lib/python3.8/doctest.py", line 1328, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[0]>", line 1, in <module>
        assert executor(program) == 0.0
      File "<doctest default[0]>", line 31, in executor
      File "/Users/nathanshammah/github/mitiq/mitiq/mitiq_pyquil/compiler.py", line 244, in basic_compile
        if isinstance(inst, Gate):
    TypeError: isinstance() arg 2 must be a type or tuple of types
```

Environment Context
-------------------

Use the `about()` function to summarize information on operating system, python version and dependencies.
```python
from mitiq import about
about()
Mitiq: A Python toolkit for implementing error mitigation on quantum computers
==============================================================================
Authored by: Mitiq team, 2020 & later (https://github.com/unitaryfund/mitiq)

Mitiq Version:	0.5.0dev

Core Dependencies
-----------------
Cirq Version:	0.9.1
NumPy Version:	1.18.5
SciPy Version:	1.4.1

Optional Dependencies
---------------------
PyQuil Version:	2.18.0
Qiskit Version:	0.12.0

Python Version:	3.8.0
Platform Info:	Darwin (x86_64)
```

Additional Python Environment Details (`pip freeze` or `conda list`):

```
Copy and paste the output of `pip freeze` or `conda list` here.
```

**Comment by rmlarose** [comment]
Can't reproduce, but doc tests aren't actually running in CI... See #535.

I propose we merge #509 first as that has many doc changes, then patch this.

**Comment by crazy4pi314** [comment]
I can reproduce the doctest failures on the current `master` release. Just checked out up to date master and ran `make doctest` in the docker container.

**Comment by crazy4pi314** [comment]
It seems like at least part of the issue is that there are doctests that require the testing framework to load an IBMQ account: https://github.com/unitaryfund/mitiq/blob/master/docs/source/guide/guide-ibmq-backends.rst#high-level-usage

I can't find anywhere where we are providing credentials for this, it seems like we should revisit how/if we want to test this.
