### ISSUE TITLE
QFT circuit containing CU1 gates cannot be converted to internal mitiq circuit

### ISSUE THREAD

**Issue by mcoggins96** [unitaryfund/mitiq#558]
Pre-Report Checklist
--------------------

- [X] I am running the latest version of mitiq
- [X] I checked to make sure that this bug has not already been reported

Issue Description
-----------------
Currently I'm trying to test the execute_with_zne() function with a QFT circuit in Qiskit. However when I run the code it gives back an error stating that the circuit cannot be converted to an internal mitiq circuit. It seems to be because it does not recognise cu1 gates which are used in the QFT circuit. 

### Code Snippet

```python
import qiskit
import mitiq

from qiskit import QuantumRegister, ClassicalRegister
from qiskit import QuantumCircuit, execute,IBMQ
from qiskit.tools.monitor import job_monitor
from qiskit.circuit.library import QFT
from mitiq import execute_with_zne

# Noise simulation packages
from qiskit.providers.aer.noise import NoiseModel
from qiskit.providers.aer.noise.errors.standard_errors import depolarizing_error

IBMQ.enable_account('ENTER API KEY HERE')
provider = IBMQ.get_provider(hub='ibm-q')

def qs_noisy_simulation(circuit: QuantumCircuit, shots: int = 1) -> float:

    #backend = provider.get_backend('ibmq_quito')
    backend = provider.get_backend('ibmq_qasm_simulator')

    job = execute(circuit, backend, shots=1000)

    job_monitor(job)

    counts = job.result().get_counts()

    print(counts)

    expval = counts["10101"] / shots
    return expval

q = QuantumRegister(5,'q')
c = ClassicalRegister(5,'c')

circuit = QuantumCircuit(q,c)
circuit.x(q[0])
circuit.x(q[2])
circuit.x(q[4])
circuit += QFT(num_qubits=5, approximation_degree=0, do_swaps=True, inverse=False, insert_barriers=True, name='qft')
circuit += QFT(num_qubits=5, approximation_degree=0, do_swaps=True, inverse=True, insert_barriers=True, name='qft')
circuit.measure(q,c)

print(circuit)

unmitigated = qs_noisy_simulation(circuit)
mitigated = execute_with_zne(circuit, qs_noisy_simulation)

print(unmitigated)
print(mitigated)
```

### Error Output

```
Traceback (most recent call last):
  File "C:\Users\macauley\AppData\Local\Programs\Python\Python37\lib\site-packages\mitiq\conversions.py", line 79, in convert_to_mitiq
    mitiq_circuit = conversion_function(circuit)
  File "C:\Users\macauley\AppData\Local\Programs\Python\Python37\lib\site-packages\mitiq\mitiq_qiskit\conversions.py", line 279, in from_qiskit
    return from_qasm(circuit.qasm())
  File "C:\Users\macauley\AppData\Local\Programs\Python\Python37\lib\site-packages\mitiq\mitiq_qiskit\conversions.py", line 292, in from_qasm
    return circuit_from_qasm(qasm)
  File "C:\Users\macauley\AppData\Local\Programs\Python\Python37\lib\site-packages\cirq\contrib\qasm_import\qasm.py", line 29, in circuit_from_qasm
    return QasmParser().parse(qasm).circuit
  File "C:\Users\macauley\AppData\Local\Programs\Python\Python37\lib\site-packages\cirq\contrib\qasm_import\_parser.py", line 519, in parse
    self.parsedQasm = self.parser.parse(lexer=self.lexer)
  File "C:\Users\macauley\AppData\Local\Programs\Python\Python37\lib\site-packages\ply\yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\Users\macauley\AppData\Local\Programs\Python\Python37\lib\site-packages\ply\yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "C:\Users\macauley\AppData\Local\Programs\Python\Python37\lib\site-packages\cirq\contrib\qasm_import\_parser.py", line 321, in p_gate_op_with_params
    self._resolve_gate_operation(args=p[5], gate=p[1], p=p, params=p[3])
  File "C:\Users\macauley\AppData\Local\Programs\Python\Python37\lib\site-packages\cirq\contrib\qasm_import\_parser.py", line 333, in _resolve_gate_operation
    raise QasmException(msg)
cirq.contrib.qasm_import.exception.QasmException: Unknown gate "cu1" at line 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mitiqTest.py", line 59, in <module>
    mitigated = execute_with_zne(circuit, qs_noisy_simulation)
  File "C:\Users\macauley\AppData\Local\Programs\Python\Python37\lib\site-packages\mitiq\zne\zne.py", line 62, in execute_with_zne
    return factory.run(qp, executor, scale_noise, int(num_to_average)).reduce()
  File "C:\Users\macauley\AppData\Local\Programs\Python\Python37\lib\site-packages\mitiq\zne\inference.py", line 533, in run
    to_run = self._generate_circuits(qp, scale_noise, num_to_average)
  File "C:\Users\macauley\AppData\Local\Programs\Python\Python37\lib\site-packages\mitiq\zne\inference.py", line 596, in _generate_circuits
    to_run.append(scale_noise(circuit, scale_factor))
  File "C:\Users\macauley\AppData\Local\Programs\Python\Python37\lib\site-packages\mitiq\conversions.py", line 144, in new_scaling_function
    mitiq_circuit, input_circuit_type = convert_to_mitiq(circuit)
  File "C:\Users\macauley\AppData\Local\Programs\Python\Python37\lib\site-packages\mitiq\conversions.py", line 82, in convert_to_mitiq
    "Circuit could not be converted to an internal Mitiq circuit. "
mitiq.conversions.CircuitConversionError: Circuit could not be converted to an internal Mitiq circuit. This may be because the circuit contains custom gates or Pragmas (pyQuil). If you think this is a bug, you can open an issue at https://github.com/unitaryfund/mitiq.
```

**Comment by rmlarose** [comment]
Thanks @mcoggins96. For now you can get around this by compiling your circuit before the call to `execute_with_zne`:

```python
circuit = qiskit.compiler.transpile(circuit, basis_gates=["u1", "u2", "u3", "cx"])
```

A more permanent fix on our end is to handle a larger set of gates which can be converted. I will remove the bug label for now, though, because we don't claim to support folding arbitrary gates.

**Comment by mcoggins96** [comment]
Thank you very much it's running now.

**Comment by rmlarose** [comment]
Will re-open to keep track of this going forward.

**Comment by rmlarose** [comment]
Superseded by #1073.
