### ISSUE TITLE
Readthedocs fails to reproduce output cells of some myst notebooks

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#573]
Read The Docs fails to execute some notebooks and just reproduces input cells without the output cells. 
Se e.g. https://mitiq.readthedocs.io/en/stable/examples/simple_landscape.html or https://mitiq.readthedocs.io/en/stable/examples/maxcut-demo.html.

It works locally, in my usual environment where `mitiq` is installed. It fails if I create a new conda environment.

The problem currently happens for `maxcut-demo.myst` and `simple_landscape.myst` and seems to be related to the
line `import mitiq`.

Indeed: 
   - `test.myst` works but
   - If I add `import mitiq` in a code cell of `test.myst`, then `make docs` fails.
   - If I execute `pip install -e .`, `make docs` works.

### Error output from local log files in docs/build/html/reports/ in a new conda environment

```
Traceback (most recent call last):
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import mitiq
import matplotlib.pyplot as plt
import numpy as np
data = np.random.rand(3, 100) * 100
data[:, :10]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-32243266b653>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mimport[0m [0mmitiq[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mdata[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mrandom[0m[0;34m.[0m[0mrand[0m[0;34m([0m[0;36m3[0m[0;34m,[0m [0;36m100[0m[0;34m)[0m [0;34m*[0m [0;36m100[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mdata[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m [0;34m:[0m[0;36m10[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'mitiq'
ModuleNotFoundError: No module named 'mitiq'
```

### Error output from Read The Docs:

```
WARNING: Execution Failed: /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/stable/docs/source/examples/maxcut-demo.myst
WARNING: Execution Failed: /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/stable/docs/source/examples/simple_landscape.myst
WARNING: Couldn't find cache key for notebook file examples/maxcut-demo.myst. Outputs will not be inserted.
  Last execution failed with traceback saved in /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/stable/docs/source/_build/html/reports/maxcut-demo.log
WARNING: Notebook code has no file extension metadata, defaulting to `.txt`
WARNING: Couldn't find cache key for notebook file examples/simple_landscape.myst. Outputs will not be inserted.
  Last execution failed with traceback saved in /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/stable/docs/source/_build/html/reports/simple_landscape.log
WARNING: Notebook code has no file extension metadata, defaulting to `.txt`
```

### Mitiq installation:
```
Mitiq: A Python toolkit for implementing error mitigation on quantum computers
==============================================================================
Authored by: Mitiq team, 2020 & later (https://github.com/unitaryfund/mitiq)

Mitiq Version:	0.6.0

Core Dependencies
-----------------
Cirq Version:	0.10.0.dev
NumPy Version:	1.20.1
SciPy Version:	1.4.1

Optional Dependencies
---------------------
PyQuil Version:	2.18.0
Qiskit Version:	0.16.4

Python Version:	3.9.1
Platform Info:	Linux (x86_64)
```

**Comment by nathanshammah** [comment]
Just for clarity: I am removing this item from the v.0.7.0 milestone as in theory out of scope. If it gets approved in the meantime, we can add it again.
