### ISSUE TITLE
Consider reverting cirq-google until deprecation warnings will disappear. 

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#716]
When we passed from `cirq` to `cirq-core`, a lot of deprecation warning appear each time we import something.
E.g. if a user tries to run:

```
python
>>> from mitiq.zne import execute_with_zne
```

The following long message appears:

<details>
--- Logging error ---
Traceback (most recent call last):
  File "/home/andrea/anaconda3/lib/python3.7/site-packages/cirq/__init__.py", line 581, in <module>
    create_attribute=True,
  File "/home/andrea/anaconda3/lib/python3.7/site-packages/cirq/_compat.py", line 546, in deprecated_submodule
    new_module = importlib.import_module(new_module_name)
  File "/home/andrea/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cirq_google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrea/anaconda3/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/home/andrea/anaconda3/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/home/andrea/anaconda3/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/home/andrea/anaconda3/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/andrea/data/mitiq/mitiq/__init__.py", line 16, in <module>
    from mitiq._about import about
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/andrea/data/mitiq/mitiq/_about.py", line 23, in <module>
    from cirq import __version__ as cirq_version
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/andrea/anaconda3/lib/python3.7/site-packages/cirq/__init__.py", line 585, in <module>
    warning("Can't import cirq.google: ", ex)
Message: "Can't import cirq.google: "
Arguments: (ModuleNotFoundError("No module named 'cirq_google'"),)
</details>

The same problem also appears in some examples in the docs. See e.g.:
https://mitiq.readthedocs.io/en/latest/examples/simple_landscape.html
https://mitiq.readthedocs.io/en/latest/examples/maxcut-demo.html#define-the-qaoa-cost-hamiltonian-using-cirq

** Proposal **
Temporarily require the full `cirq` package, until the warning disappear?
They will probably fix this at some point: https://github.com/quantumlib/Cirq/issues/4106

**Comment by andreamari** [comment]
@rmlarose

**Comment by nathanshammah** [comment]
+1.

**Comment by rmlarose** [comment]
The warning showing up in docs is not good. Thanks for noting this. I'm fine with listing `cirq` in requirements to fix this. Alternatively, we can list `cirq-google` in dev_requirements and that will get rid of the warning in docs.

Note that the warning will be present until Cirq 0.14 (https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/__init__.py#L584-L594), which may be a while.

> When we passed from `cirq` to `cirq-core`, a lot of deprecation warning appear each time we import something.
> E.g. if a user tries to run:
> 
> ```
> python
> >>> from mitiq.zne import execute_with_zne
> ```
> 
> The following long message appears:

This I'm not too concerned about. If they want to get rid of the warning they can install cirq-google in their environment.

**Comment by nathanshammah** [comment]
I like the proposal of having back again `cirq` in requirements.
